#!/bin/bash

# settings to control internal logic
run_interactive=true
run_batch=false

echo "sourcing local settings ..."
FILE="myenv.env"
if [ -f $FILE ]; then
    echo "File $FILE exists."
    source myenv.env
else
    echo "File $FILE does not exist, cannot continue"
    exit
fi
FILE="test/can.ex2"
if [ -f $FILE ]; then
    echo "File $FILE exists."
else
    echo "File $FILE does not exist, cannot continue"
    exit
fi


paraview=$CINEMATESTING_PARAVIEW
pvbatch=$CINEMATESTING_PVBATCH
filedriver=$CINEMATESTING_FILEDRIVER
browser=$CINEMATESTING_BROWSER

echo "Local definitions:"
echo "  Paraview: ${paraview}"
echo "  Browser : ${browser}"
echo ""

echo "Deleting data ..."
rm -rf data/interactive
rm -rf data/batch
rm -rf data/test_*
mkdir data/interactive
mkdir data/batch

if $run_interactive ; then
    echo "Running GEOMETRY tests ..."
    echo "  geometry ..."
    $paraview --test-script=test/test_cdb_geom.xml --exit
    echo "  geometry and images ..."
    $paraview --test-script=test/test_cdb_geom_and_images.xml --exit
    # echo "Running IMAGE tests ..."
    # echo "  static camera ..."
    # $paraview --test-script=test/test_cdb_static_camera.xml --exit
    # echo "  phi-theta camera ..."
    # $paraview --test-script=test/test_cdb_phi_theta.xml --exit
    # echo "  two view static camera ..."
    # $paraview --test-script=test/test_cdb_twoviews_static_camera.xml --exit
    # echo "  two view phi-theta camera ..."
    # $paraview --test-script=test/test_cdb_twoviews_phi_theta.xml --exit
else
    echo "NOT running INTERACTIVE  tests ..."
fi

if $run_batch ; then
    echo "Running tests ..."
    echo "  static camera ..."
    sed -i '' "s/'can.ex2'/'input'/g" data/test_cdb_static_camera.py
    mpirun -np 1 $pvbatch -sym $filedriver "$FILE" data/test_cdb_static_camera.py
    echo "  phi-theta camera ..."
    sed -i '' "s/'can.ex2'/'input'/g" data/test_cdb_phi_theta.py
    mpirun -np 1 $pvbatch -sym $filedriver "$FILE" data/test_cdb_phi_theta.py
    echo "  two view static camera ..."
    sed -i '' "s/'can.ex2'/'input'/g" data/test_cdb_twoviews_static_camera.py
    mpirun -np 1 $pvbatch -sym $filedriver "$FILE" data/test_cdb_twoviews_static_camera.py
    echo "  two view phi-theta camera ..."
    sed -i '' "s/'can.ex2'/'input'/g" data/test_cdb_twoviews_phi_theta.py
    mpirun -np 1 $pvbatch -sym $filedriver "$FILE" data/test_cdb_twoviews_phi_theta.py
else
    echo "NOT running INTERACTIVE  tests ..."
fi

echo "Inspecting results ..."
case "$OSTYPE" in
  darwin*)
        open -a $browser cinema_explorer.html
        open -a $browser cinema_compare.html;;
  solaris*) echo "Cannot view results" ;;
  linux*)   echo "Cannot view results" ;;
  bsd*)     echo "Cannot view results" ;;
  msys*)    echo "Cannot view results" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac
