#!/bin/bash

# get definitions from local files and check before running
# -------------------------------------------------------------------------
echo "Sourcing local settings ..."
ENVFILE="myenv.env"
if [ -f $ENVFILE ]; then
    echo "File $ENVFILE exists."
    source myenv.env
else
    echo "File $ENVFILE does not exist, cannot continue"
    exit
fi

# Data set
echo "Checking for test data ..."
CANFILE="test/can.ex2"
if [ -f $CANFILE ]; then
    echo "File $CANFILE exists."
else
    echo "File $CANFILE does not exist, cannot continue"
    exit
fi

# Define the local executables, etc.
# -------------------------------------------------------------------------
paraview=$CINEMATESTING_PARAVIEW
pvbatch=$CINEMATESTING_PVBATCH
filedriver=$CINEMATESTING_FILEDRIVER
browser=$CINEMATESTING_BROWSER
echo "Local definitions:"
echo "  Paraview   : ${paraview}"
echo "  pvbatch    : ${pvbatch}"
echo "  filedriver : ${filedriver}"
echo "  Browser    : ${browser}"
echo ""

# Define the tests to run
# Comment out any that should not run
# -------------------------------------------------------------------------
run_interactive=true
run_batch=true
clean=true
tests=(
    "test_cdb_geom"
    "test_cdb_geom_and_images"
    "test_cdb_phi_theta"
    "test_cdb_static_camera"
    "test_cdb_twoviews_static_camera"
    "test_cdb_twoviews_phi_theta"
)


# delete any previous data
# -------------------------------------------------------------------------
if $clean ; then
    ./clean
fi


# Run all tests
# -------------------------------------------------------------------------

# Interactive tests
if $run_interactive ; then
    echo "Running INTERACTIVE tests ..."
    for i in "${tests[@]}"
    do
        echo "  $i.xml"
        $paraview --test-script=test/$i.xml --exit
    done
else
    echo "NOT running INTERACTIVE  tests ..."
fi

# Batch tests
if $run_batch ; then
    echo "Running BATCH tests ..."
    for i in "${tests[@]}"
    do
        echo "  $i.xml"
        # sed -i '' "s/can\.ex2/input/g" data/$i.py
        sed -i '' "s/'can.ex2'/'input'/g" data/$i.py
        mpirun -np 1 $pvbatch -sym $filedriver "$CANFILE" data/$i.py
    done
else
    echo "NOT running INTERACTIVE  tests ..."
fi

# Inspect the results
# -------------------------------------------------------------------------
echo "Inspecting results ..."
case "$OSTYPE" in
  darwin*)
        open -a $browser cinema_explorer.html
        open -a $browser cinema_compare.html;;
  solaris*) echo "Cannot view results" ;;
  linux*)   echo "Cannot view results" ;;
  bsd*)     echo "Cannot view results" ;;
  msys*)    echo "Cannot view results" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac

echo "Completed tests"
echo " "
