#!/bin/bash

echo "sourcing local settings ..."
FILE="myenv.env"
if [ -f $FILE ]; then
    echo "File $FILE exists."
    source myenv.env
else
    echo "File $FILE does not exist, cannot continue"
    exit
fi
FILE="test/can.ex2"
if [ -f $FILE ]; then
    echo "File $FILE exists."
else
    echo "File $FILE does not exist, cannot continue"
    exit
fi


paraview=$CINEMATESTING_PARAVIEW
pvbatch=$CINEMATESTING_PVBATCH
filedriver=$CINEMATESTING_FILEDRIVER
browser=$CINEMATESTING_BROWSER

echo "Local definitions:"
echo "  Paraview: ${paraview}"
echo "  Browser : ${browser}"
echo ""

echo "Deleting data ..."
rm -rf data/test_*

echo "Running tests ..."
echo "  static camera ..."
$paraview --test-script=test/test_cdb_static_camera.xml --exit
echo "  phi-theta camera ..."
$paraview --test-script=test/test_cdb_phi_theta.xml --exit
echo "  two view static camera ..."
$paraview --test-script=test/test_cdb_twoviews_static_camera.xml --exit
echo "  two view phi-theta camera ..."
$paraview --test-script=test/test_cdb_twoviews_phi_theta.xml --exit

echo "Running catalyst tests ..."
echo "  static camera ..."
mpirun -np 1 $pvbatch -sym $filedriver "$FILE" catalyst_test/test_cdb_static_camera_catalyst.py

echo "Inspecting results ..."
open -a $browser cinema_compare.html
open -a $browser cinema_explorer.html
